### ISSUE TITLE
ReviewEventsGUI disagreement about bad strides with PlotParamsGUI

### ISSUE THREAD

**Issue by willpower2727** [pabloi/labTools#10]
When processing a subject and there are bad steps, deleting the bad events in ReviewEventsGUI does not remove them from the plot generated by PlotParamsGUI. I know of two cases now where I have been unable to remove a bad stride.

For an example, consider C0014 on the shared drive. The offending trial is during adaptation trial #7 or #8. As you can see from these images the spatial parameters in the revieweventsgui do not contain the large error point as seen in the matlab figure generated by PlotParamsGUI.

Z:\shared\Exp001\raw\C0014\

![net2](https://cloud.githubusercontent.com/assets/10742358/9933322/3badae02-5d18-11e5-9b35-ccf33b4f719d.jpg)
![untitled](https://cloud.githubusercontent.com/assets/10742358/9933323/3bafc08e-5d18-11e5-9885-e2f03085e768.jpg)
![untitled1](https://cloud.githubusercontent.com/assets/10742358/9933350/5b569214-5d18-11e5-900e-ec65c1d92e14.jpg)

**Comment by pabloi** [comment]
ReviewEventsGUI saves an experimentData object, while PlotParamsGUI loads and plots adaptationData objects. After making changes in ReviewEventsGUI you need to generate a new adaptationData object (using makeDataObj) and save it to a file (usually named usernameParams.mat)

Is this still an issue if those steps are taken?

**Comment by willpower2727** [comment]
Does this mean that the ReviewEventsGUI does not actually alter the __Params.mat? Wouldn't it be more intuitive to include a call to makeDataObj() when the user presses the "write to disk" button?

**Comment by pabloi** [comment]
Correct, the only file that is altered is the one that is loaded.

Perhaps it would be desirable to generate the Params file when writing to
disk, but the subject would need to specify the name of this new file
(using __Params.mat is actually up to each user, doesn't need to be like
that). Be aware that calling makeDataObj() generates the adaptationData
object, but does not write it to any file. We would need to issue a save()
command to generate that.

Summary:
If you want to add the new functionality of writing the __Params file, go
ahead. However, this are the requirements for doing that:
          --- Ask subject for filename to save, or AT LEAST issue a warning
that __Params will be overwritten (if it exists) and ask the subject to
confirm.


On Thu, Sep 24, 2015 at 8:34 AM, willpower2727 <notifications@github.com>
wrote:

> Does this mean that the ReviewEventsGUI does not actually alter the
> __Params.mat? Wouldn't it be more intuitive to include a call to
> makeDataObj() when the user presses the "write to disk" button?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pabloi/labTools/issues/10#issuecomment-142915357>.
>



-- 
Pablo A. Iturralde

**Comment by willpower2727** [comment]
Ok, I've narrowed the issue. Bad events are still plotted by PlotParamsGUI when it calls adaptationData.PlotAvgTimeCourse()

The ReviewEventsGUI does indeed save over the old params file when "write to disk" is pressed.

Loading a params file by hand and calling adaptationData.plotParamTimeCourse() does NOT plot bad strides.

**Comment by pabloi** [comment]
Not sure I understand.

You are asserting:
1) The params file IS re-written upon hitting 'Write to Disk'.
Q: How does the software know which file to re-write?  Does it assume that
it lives in the same file as the loaded file and it just appends 'params'
at the end of the filename?
2) "Bad events are still plotted by PlotParamsGUI when it calls
adaptationData.PlotAvgTimeCourse()"
Q: this assertion is meaningless unless you specify which adaptationData
objects are being passed as parameters, and where those were loaded from.
Can you specify?



On Thu, Sep 24, 2015 at 10:40 AM, willpower2727 <notifications@github.com>
wrote:

> Ok, I've narrowed the issue. Bad events are still plotted by PlotParamsGUI
> when it calls adaptationData.PlotAvgTimeCourse()
>
> The ReviewEventsGUI does indeed save over the old params file when "write
> to disk" is pressed.
>
> Loading a params file by hand and calling
> adaptationData.plotParamTimeCourse() does NOT plot bad strides.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pabloi/labTools/issues/10#issuecomment-142949014>.
>



-- 
Pablo A. Iturralde

**Comment by willpower2727** [comment]
Line 795 of ReviewEventsGUI, saves over the expData object

Line 801 creates new adaptData in memory for the GUI to use.

**Comment by willpower2727** [comment]
Ignore claim about PlotAvgTimeCourse(), I was using a S matrix that was still using old data.
