### ISSUE TITLE
EMG processing for 1 base (1-16 emg) only

### ISSUE THREAD

**Issue by willpower2727** [pabloi/labTools#12]
Yashar's study will only use 15 emg sensors, 1 base, but labtools is only currently setup to process emg from both bases.

Is there an easy fix to let labtools know that it doesn't need to synchronize? It crashes when trying to synchronize:

Error using griddedInterpolant
Interpolation requires at least two sample points in each dimension.

Error in interp1>Interp1DStripNaN (line 233)
    F = griddedInterpolant(xi,vi,method);

Error in interp1 (line 171)
        VqLite = Interp1DStripNaN(X,V,Xq,F.Method);

Error in findTimeLag (line 31)
P2=interp1(0:length(P)-1,P,aux,'spline'); %For sub-sample resolution

Error in estimateDopplerShift (line 36)
        [~,~,t(i)]=findTimeLag(aux1,aux2,1,Inf);

Error in matchSignals (line 60)
[relativeShift,~] = estimateDopplerShift(signal1,alignedSignal2);

Error in loadTrials (line 257)
        [~,timeScaleFactorA,lagInSamplesA,~] = matchSignals(refAux,aux(:,1));

Error in loadSubject (line 83)
rawTrialData=loadTrials(trialMD,fileList,secFileList,info);

Error in c3d2mat (line 23)
    [expData,rawExpData,adaptData]=loadSubject(info,eventClass{answer});

Error in interp1>Interp1DStripNaN (line 233)
    F = griddedInterpolant(xi,vi,method);

Error in interp1 (line 171)
        VqLite = Interp1DStripNaN(X,V,Xq,F.Method);

Error in findTimeLag (line 31)
P2=interp1(0:length(P)-1,P,aux,'spline'); %For sub-sample resolution

Error in estimateDopplerShift (line 36)
        [~,~,t(i)]=findTimeLag(aux1,aux2,1,Inf);

Error in matchSignals (line 60)
[relativeShift,~] = estimateDopplerShift(signal1,alignedSignal2);

Error in loadTrials (line 257)
        [~,timeScaleFactorA,lagInSamplesA,~] = matchSignals(refAux,aux(:,1));

Error in loadSubject (line 83)
rawTrialData=loadTrials(trialMD,fileList,secFileList,info);

Error in c3d2mat (line 23)
    [expData,rawExpData,adaptData]=loadSubject(info,eventClass{answer});

**Comment by pabloi** [comment]
The easiest fix I can think of is to comment out all code related to the
second base in loadTrials

I thought we had fixed this issue in the past, as I have conducted some
experiments using a single emg base. Could you check the changelog for this
function and see if we regressed something?

**Comment by pabloi** [comment]
I think I understand what is happening: you get an error because there is
no sync signal, not because there is a single base. Even if you have a
single base I would recommend synchronization because there is a delay in
the emg activity data stream. If you didnt record one , just try disabling
synchronization altogether. Once again, this needs to happen in loadTrials.

**Comment by willpower2727** [comment]
We did use a biodex sensor connected to the forceplates. I have verified that there is a signal on this channel

**Comment by pabloi** [comment]
That is strange. The error does seem to say that there was an issue
synching the first base, not the second one.

Have you found a workaround?

**Comment by willpower2727** [comment]
Ok, I updated labtools and got a different error, I apologize for the confusion. I've attached screen shots of what the inputs are and the error during synchronization. I'm still looking into this to find a solution...
![c3d2matscreenshot](https://cloud.githubusercontent.com/assets/10742358/10551249/e088aec8-7419-11e5-9d53-71a0fe40b1ab.jpg)
![c3d2matscreenshot2](https://cloud.githubusercontent.com/assets/10742358/10551250/e0891b10-7419-11e5-8b16-b95a52c776db.jpg)

**Comment by willpower2727** [comment]
I think I found a solution. I'll commit the update once I know it works...

**Comment by willpower2727** [comment]
Resolved for now, I think there were some lines of code that did not check if there was a second file before executing. It was a rare case, because the first trial had bad synch data. The remaining files were fine
